[package]
name = "ssb-keyfile"
version = "0.1.0"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
description = "Keyfile operations for ssb."
repository = "https://github.com/AljoschaMeyer/ssb-keyfile-rs"
readme = "README.md"
license = "GPL-3.0"

[dependencies]
ssb-common = { git = "https://github.com/AljoschaMeyer/ssb-common-rs" }
regex = "0.2.6"
lazy_static = "1.0.0"