[package]
name = "ssb-keyfile"
version = "0.4.0"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
description = "Keyfile operations for ssb."
repository = "https://github.com/AljoschaMeyer/ssb-keyfile-rs"
readme = "README.md"
license = "GPL-3.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.10"
ssb-crypto = { version = "0.2.1", default_features = false, features = ["b64"] }
thiserror = "1.0.20"
base64 = "0.12.3"
